{% set name = "hexlite" %}
{% set version = "1.0.1" %}
{% set file_ext = "tar.gz" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.python.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools
    - python
    - ply
    - potassco::clingo
  run:
    - python
    - ply
    - potassco::clingo

test:
  imports:
    - dlvhex
    - hexlite
    - hexlite.ast

about:
  home: https://github.com/hexhex/hexlite
  license: GNU General Public License v3 (GPLv3)
  license_family: GPL3
  summary: HEXLite Python-based solver for a fragment of HEX
  description: "see https://github.com/hexhex/hexlite"

extra:
  recipe-maintainers: 'Peter Schueller <schueller.p@gmail.com>'
